-- MuseAI 平台库 0048：§15 第 3 层**补偿轮询**要用的两条索引（不加表、不加列）。
--
-- ═══════════════════════════════════════════════════════════════════════════
-- 补的是哪个缺口
-- ═══════════════════════════════════════════════════════════════════════════
-- `safety::semantic` 的模块头一直挂着这条如实登记的遗留：
--
--   ⚠️ `MemQueue` 是进程内内存队列，**不持久**。进程重启时在飞的复核任务会丢，
--      那一拍的事件就停留在 `approved` 且再无人复核。……接 Redis 实现或加一条
--      「扫尾未复核拍」的补偿轮询即可闭合。
--
-- 本批次走的是**补偿轮询**那条。选它而不是 Redis，理由只有一条：
-- **可靠性来自「事实的对账」，不是「队列的承诺」。** 一个持久队列只能保证
-- 「已经入队的任务不丢」；它对「压根没入队」（开关当时是关的、tick 走的是
-- blocked / cas_conflict 分支根本没到那行代码、topic 配错）一无所知。
-- 而补偿轮询是拿 `world_ticks ⋈ safety_recheck_runs` **重新算一遍待办**——
-- 它覆盖的是「这一拍到底有没有被复核过」这个事实本身，与任务当初有没有入队无关。
--
-- 🔵 顺带闭合了一个此前没登记过的洞：`runtime` 里 blocked / cas_conflict 两条收尾路径
-- 也把 `world_ticks.status` 写成 `'done'`，但它们**不经过** `commit_tick` 末尾那行
-- `enqueue_after_commit`。那些拍如果带着 approved 事件，此前从来没有被第 3 层看过一眼。
--
-- ═══════════════════════════════════════════════════════════════════════════
-- 为什么只加索引，不加表
-- ═══════════════════════════════════════════════════════════════════════════
-- 轮询是**无状态**的：它不记「我上次扫到哪」，每次都现算。这不是偷懒，是刻意的——
-- 若它维护自己的游标/计数器，那么它一旦死掉，那些数字会**冻结在健康的样子**，
-- 而真实缺口在背后继续长。从 `world_ticks ⋈ safety_recheck_runs` 现算的缺口数
-- 则是「轮询死了也照样变大」的量，运营面读到的是病情，不是病历。
--
-- 代价是每次扫描都要落到这两个连接条件上，而它们此前都没有索引：
--
--   ① `world_events(world_id, tick_no, moderation)`
--      既有索引只有 `(world_id, sequence)` 与 `(occurred_at)`。轮询的存在性判定
--      （「这一拍还有没有 approved 的事件」）与**第 3 层的热路径**
--      （`load_candidates`：`WHERE world_id=? AND tick_no=? AND moderation='approved'`）
--      走的是同一个形状——后者从上线起就在按世界全扫，这条索引把它一并修了。
--
--   ② `world_ticks(status, finished_at)`
--      既有索引是 `(world_id, tick_no)` 唯一键、`(world_id, status)`、`(world_id, off_peak)`，
--      全部以 `world_id` 打头。轮询要问的是**跨世界**的「最近这段时间里落定的拍」，
--      没有这条索引就是 `world_ticks` 全表扫，而这张表只增不减。
--      ⚠️ 这正是补偿轮询最容易写坏的地方：一个「每 5 分钟全表扫一遍只增不减的表」的
--      后台任务，上线当天没人看得出来，半年后变成数据库上最贵的那条查询。
--
-- 双库可移植（db.rs 约定）：纯 `CREATE INDEX`，无方言特性（无 partial index / 无 INCLUDE /
-- 无 JSONB / 无 NOW()）。`finished_at` 可空——两库对 NULL 的索引行为在此处无差别，
-- 因为查询侧一律带 `finished_at >= ?`（NULL 不满足，自然被排除，也正是想要的语义：
-- 没落定的拍不该被扫尾）。

-- ① 第 3 层候选装载 + 轮询的存在性判定共用。
CREATE INDEX idx_world_events_tick_mod ON world_events(world_id, tick_no, moderation);

-- ② 轮询的跨世界时间窗扫描（`status='done'` 且 `finished_at` 落在窗口内）。
CREATE INDEX idx_world_ticks_status_finished ON world_ticks(status, finished_at);
